### ISSUE TITLE
nRF module

### ISSUE THREAD

**Issue by n0tAv1ru5** [smoochiee/Noisy-boy-esp32-Bluetooth-jammer#1]
Can i use ebyte E01-ML01DP5 module for nRF module?
![Screenshot 2024-09-20 204725](https://github.com/user-attachments/assets/a26adee5-23dd-4090-89b6-8174b07472db)

**Comment by smoochiee** [comment]
> Can i use ebyte E01-ML01DP5 module for nRF module? ![Screenshot 2024-09-20 204725](https://private-user-images.githubusercontent.com/168189222/369429514-a26adee5-23dd-4090-89b6-8174b07472db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzUxNDgsIm5iZiI6MTcyNzA3NDg0OCwicGF0aCI6Ii8xNjgxODkyMjIvMzY5NDI5NTE0LWEyNmFkZWU1LTIzZGQtNDA5MC04OWI2LTgxNzRiMDc0NzJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwNzAwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzE2YjdjMTZjODZjYTcyODgyNjE5ZGJhYzMxYzg3ZjEyMzRlMjc1Y2Y2YjdkZGU2MmEwMjgyYzljMDhjMWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hjXEpiiw55ycSLKAHfnEI7BpuZORD6HmlN8fHefrCLA)

yes
