### ISSUE TITLE
Suggestion: Add Debouncing for GPIO4 Button

### ISSUE THREAD

**Issue by Cabbarot** [smoochiee/Noisy-boy-esp32-Bluetooth-jammer#10]
Hi there!
First of all, thank you for this amazing project! I’ve installed the version of NoisyBoy where GPIO4 is used as the jammer switch (instead of the boot button), and it’s working great overall. However, I noticed a small quirk with the button connected to GPIO4.

Sometimes the button doesn’t respond to presses, and I suspect this might be due to a lack of debouncing. This isn’t a big deal, but I thought it might be helpful to suggest adding a debounce mechanism to make the button handling even more robust.

Possible Ideas:
Software Debouncing: Adding a small delay (e.g., 50 ms) after detecting a button press or sampling the button state multiple times to confirm the press.
Hardware Debouncing: Recommending users add a small capacitor (e.g., 0.1 µF) across the button terminals to filter out noise.
This should make the button response more consistent and improve the overall user experience.

Thanks again for your awesome work on NoisyBoy! Let me know if I can help test any changes or provide more details.

**Comment by smoochiee** [comment]
use the diy pcb firmware...have debounce...gpio 27 for led
