### ISSUE TITLE
This isnt even an issue

### ISSUE THREAD

**Issue by Lgndwilloske** [smoochiee/Noisy-boy-esp32-Bluetooth-jammer#3]
I have to say, there must of been some time and effort put into this. The code is awesome and it works brilliantly.

Thanks - Willy

**Comment by smoochiee** [comment]
> I have to say, there must of been some time and effort put into this. The code is awesome and it works brilliantly.
> 
> Thanks - Willy

thanks

**Comment by Marakesh85** [comment]
> I have to say, there must of been some time and effort put into this. The code is awesome and it works brilliantly.
> 
> Thanks - Willy

I wonder how you tested it. Ive tested it with my Anker bluetooth speaker and it has no effect. 
Any special configurations youve done?
I cant get it to work.

Tested with wroom32u
2x Rnf24l01 pn+lna

**Comment by Lgndwilloske** [comment]
aye, I had a August headset that i tested, same hardware as you maybe reflash?

**Comment by Marakesh85** [comment]
> aye, I had a August headset that i tested, same hardware as you maybe reflash?

Ive Reflashed it serveral times.^^ i dont know why it doesnt work. Im going to test it with some other devices

**Comment by Lgndwilloske** [comment]
your clicking the boot button?

**Comment by Marakesh85** [comment]
> your clicking the boot button?

Jepp.

**Comment by smoochiee** [comment]
> > your clicking the boot button?
> 
> Jepp.

you need to configure it first...follow step 3

**Comment by Marakesh85** [comment]
I had it configured :/ im going to wire it again directly to the esp with jumper wires instead of breadboard connections. I also have a soldered one that is also not working. The thing is that i have no Option to test the nrf modules if they really work or if they are damaged.-_-

**Comment by smoochiee** [comment]
> I had it configured :/ im going to wire it again directly to the esp with jumper wires instead of breadboard connections. I also have a soldered one that is also not working. The thing is that i have no Option to test the nrf modules if they really work or if they are damaged.-_- 

i hate breadboard.. sometimes they are not working😂

**Comment by dgorbatko** [comment]
Hi, quick question, i have M5stickc plus 2 based on esp32. But it has limited connectors. So i can physicaly connect only one NRF24 (I connected and it works). So to get stronger jamming effect, like you did with dual nrf24 (but you did it on two separated channels), so if i connect two nrf24 in parallel to my esp32 m5stickc pluse 2, will it work? And if it works will the jamming effect be stornger?

**Comment by smoochiee** [comment]
the jamming effect will be the same...same channel...does not make sense...if you want to increase range buy amplifier...

**Comment by Kaanseniyesin** [comment]
i can see it transmitting and then it stops transmitting i am using esp32 30 pin development with nrf24l01
