### ISSUE TITLE
Boot Button

### ISSUE THREAD

**Issue by Lgndwilloske** [smoochiee/Noisy-boy-esp32-Bluetooth-jammer#5]
How do i change theboot button?? and what can i change it to??

**Comment by smoochiee** [comment]
> How do i change theboot button?? and what can i change it to??

add button on GPIO4 and flash the new firmware https://smoochiee.github.io/Noisy-boy-esp32-Bluetooth-jammer/flash

**Comment by Lgndwilloske** [comment]
so, do i solder 2 wires to gpio4?

**Comment by smoochiee** [comment]
> so, do i solder 4 wires to gpio4? the button i have has 4 solder points
you can search google on how to do it...

**Comment by Lgndwilloske** [comment]
There is nothing online that helps.

**Comment by Lgndwilloske** [comment]
The button i have has 4 pins, I have soldered one to gpio 4 what about the second one?

**Comment by Lgndwilloske** [comment]
It also doesent jam anything for some reason, I have sorted out the boot button btw it'd gpio 4 and ground

**Comment by smoochiee** [comment]
> It also doesent jam anything for some reason, I have sorted out the boot button btw it'd gpio 4 and ground

again..you need to configure it on webrowser .follow instructions..read
